--------------------------------------------
--This project was develop using
--Oracle database 11g
---------------------------------------------
--For further information, please check the
--Readme, where i provided all the diagrams
--in order to understand the data model.
---------------------------------------------
--@author DaRk452
--@email imunoz@redeshost.cl
---------------------------------------------


CREATE TABLE "NIVEL"
( "ID_NIVEL" NUMBER(∗,0) NOT NULL ENABLE,
"NOM_NIVEL" NUMBER(∗,0),
CONSTRAINT "NIVEL_PK" PRIMARY KEY ("ID_NIVEL"));


CREATE TABLE "PERSONAL"
( "NUM_CORRELATIVO" NUMBER(∗,0) NOT NULL ENABLE,
"DV" CHAR(1) NOT NULL ENABLE,
"NOMBRES" VARCHAR2(255),
"APATERNO" VARCHAR2(255),
"AMATERNO" VARCHAR2(255),
"FNAC" DATE,
"CALLE" VARCHAR2(500),
"NUM" VARCHAR2(10),
"COD_POSTAL" VARCHAR2(10),
"CIUDAD" VARCHAR2(255),
"REGION" VARCHAR2(255),
CONSTRAINT "PERSONAL_PK" PRIMARY KEY ("NUM_CORRELATIVO", "
DV"));


CREATE TABLE "PERSONALCELULAR"
( "CELULAR" NUMBER(∗,0) NOT NULL ENABLE,
"NUM_CORRELATIVO" NUMBER(∗,0) NOT NULL ENABLE,
"DV" CHAR(1) NOT NULL ENABLE,
CONSTRAINT "PERSONALCELULAR_PK" PRIMARY KEY ("CELULAR", "
NUM_CORRELATIVO","DV"),
CONSTRAINT "PERSONALCELULAR_PERSONAL_FK" FOREIGN KEY ("
NUM_CORRELATIVO", "DV")
REFERENCES "PERSONAL" ("NUM_CORRELATIVO", "DV"));


CREATE TABLE "PERSONALMAIL"
( "MAIL" VARCHAR2(500) NOT NULL ENABLE,
"NUM_CORRELATIVO" NUMBER(∗,0) NOT NULL ENABLE,
"DV" CHAR(1) NOT NULL ENABLE,
CONSTRAINT "PERSONALMAIL_PK" PRIMARY KEY ("MAIL", "
NUM_CORRELATIVO", "DV"),
CONSTRAINT "PERSONALMAIL_PERSONAL_FK" FOREIGN KEY ("
NUM_CORRELATIVO", "DV") REFERENCES "PERSONAL" ("
NUM_CORRELATIVO", "DV"));


CREATE TABLE "DOCENTE"
("NUM_CORRELATIVO" NUMBER(∗,0) NOT NULL ENABLE,
"DV" CHAR(1) NOT NULL ENABLE,
CONSTRAINT "FK_ASS_2" FOREIGN KEY ("
PERSONAL_NUM_CORRELATIVO", "PERSONAL_DV")
REFERENCES "PERSONAL" ("NUM_CORRELATIVO", "DV"));


CREATE TABLE "CARGO"
( "ID_CARGO" NUMBER(∗,0) NOT NULL ENABLE,
"NOM_C" VARCHAR2(255),
"DESC_C" VARCHAR2(500),
CONSTRAINT "CARGO_PK" PRIMARY KEY ("ID_CARGO"));


CREATE TABLE "NO_DOCENTE"
( "NUM_CORRELATIVO" NUMBER(∗,0) NOT NULL ENABLE,
"DV" CHAR(1) NOT NULL ENABLE,
CONSTRAINT "NO_DOCENTE_PK" PRIMARY KEY ("
PERSONAL_NUM_CORRELATIVO", "PERSONAL_DV"),
CONSTRAINT "FK_ASS_1" FOREIGN KEY ("
PERSONAL_NUM_CORRELATIVO", "PERSONAL_DV") REFERENCES "
PERSONAL" ("NUM_CORRELATIVO", "DV"),
CONSTRAINT "NO_DOCENTE_CARGO_FK" FOREIGN KEY ("ID_CARGO")
REFERENCES "CARGO" ("ID_CARGO"));


CREATE TABLE "CURSO"
( "LETRA" CHAR(1) NOT NULL ENABLE,
"YEAR" NUMBER(∗,0),
"ID_NIVEL" NUMBER(∗,0) NOT NULL ENABLE,
"NUM_CORRELATIVO" NUMBER(∗,0),
"DV" CHAR(1),
CONSTRAINT "CURSO_PK" PRIMARY KEY ("LETRA", "ID_NIVEL"),
CONSTRAINT "CURSO_DOCENTE_FK" FOREIGN KEY ("
NUM_CORRELATIVO", "DV") REFERENCES "DOCENTE" ("
PERSONAL_NUM_CORRELATIVO", "PERSONAL_DV"),
CONSTRAINT "CURSO_NIVEL_FK" FOREIGN KEY ("ID_NIVEL")
REFERENCES "NIVEL" ("ID_NIVEL"));


CREATE TABLE "ASIGNATURA"
( "ID_ASIG" NUMBER(∗,0) NOT NULL ENABLE,
"NOM_ASIG" VARCHAR2(255),
"LETRA" CHAR(1),
"ID_NIVEL" NUMBER(∗,0),
"NUM_CORRELATIVO" NUMBER(∗,0),
"DV" CHAR(1),
CONSTRAINT "ASIGNATURA_PK" PRIMARY KEY ("ID_ASIG"),
CONSTRAINT "ASIGNATURA_CURSO_FK" FOREIGN KEY ("LETRA", "
ID_NIVEL") REFERENCES "CURSO" ("LETRA", "ID_NIVEL"),
CONSTRAINT "ASIGNATURA_DOCENTE_FK" FOREIGN KEY ("
NUM_CORRELATIVO", "DV") REFERENCES "DOCENTE" ("
PERSONAL_NUM_CORRELATIVO", "PERSONAL_DV"));


CREATE TABLE "PROGRAMA_TIPO"
( "ID_PT" NUMBER(∗,0) NOT NULL ENABLE,
"NOM_PT" VARCHAR2(255),
"ABREV" VARCHAR2(10),
CONSTRAINT "PROGRAMA_TIPO_PK" PRIMARY KEY ("ID_PT"));


CREATE TABLE "DETALLE_PROGRAMA"
( "ID_DP" NUMBER(∗,0) NOT NULL ENABLE,
"NOM_DP" VARCHAR2(255),
"DESC_DP" VARCHAR2(1000),
"ID_PT" NUMBER(∗,0),
"ID_ASIG" NUMBER(∗,0),
CONSTRAINT "DETALLE_PROGRAMA_PK" PRIMARY KEY ("ID_DP"),
CONSTRAINT "DETALLE_PROGRAMA_ASIGNATURA_FK"
FOREIGN KEY ("ID_ASIG") REFERENCES "ASIGNATURA" ("ID_ASIG"),
CONSTRAINT "DETALLE_PROGRAMA_PROG_TIPO_FK"
FOREIGN KEY ("ID_PT") REFERENCES "PROGRAMA_TIPO" ("ID_PT"));


CREATE TABLE "PLANIFICACION"
( "ID_PLAN" NUMBER(∗,0) NOT NULL ENABLE,
"TIPO_PLAN" VARCHAR2(10),
"ULT_ESTADO" VARCHAR2(255),
"FCREACION" DATE,
"ULT_MODIF" DATE,
"NUM_CORRELATIVO" NUMBER(∗,0),
"DV" CHAR(1),
"ID_ASIG" NUMBER(∗,0),
CONSTRAINT "PLANIFICACION_PK" PRIMARY KEY ("ID_PLAN"),
CONSTRAINT "PLANIFICACION_ASIGNATURA_FK" FOREIGN KEY ("
ID_ASIG")
REFERENCES "ASIGNATURA" ("ID_ASIG"),
CONSTRAINT "PLANIFICACION_DOCENTE_FK" FOREIGN KEY ("
NUM_CORRELATIVO", "DV")
REFERENCES "DOCENTE" ("PERSONAL_NUM_CORRELATIVO", "
PERSONAL_DV"));


CREATE TABLE "PLAN_ANUAL"
( "PLANIFICACION_ID_PLAN" NUMBER(∗,0) NOT NULL ENABLE,
CONSTRAINT "PLAN_ANUAL_PK" PRIMARY KEY ("
PLANIFICACION_ID_PLAN"),
CONSTRAINT "FK_ASS_11" FOREIGN KEY ("PLANIFICACION_ID_PLAN")
REFERENCES "PLANIFICACION" ("ID_PLAN"));


CREATE TABLE "PLAN_UNIDAD"
( "PLANIFICACION_ID_PLAN" NUMBER(∗,0) NOT NULL ENABLE,
CONSTRAINT "PLAN_UNIDAD_PK" PRIMARY KEY ("
PLANIFICACION_ID_PLAN"),
CONSTRAINT "FK_ASS_12" FOREIGN KEY ("PLANIFICACION_ID_PLAN")
REFERENCES "PLANIFICACION" ("ID_PLAN"));


CREATE TABLE "PLAN_CLASE"
( "PLANIFICACION_ID_PLAN" NUMBER(∗,0) NOT NULL ENABLE,
CONSTRAINT "PLAN_CLASE_PK" PRIMARY KEY ("
PLANIFICACION_ID_PLAN"),
CONSTRAINT "FK_ASS_13" FOREIGN KEY ("PLANIFICACION_ID_PLAN")
REFERENCES "PLANIFICACION" ("ID_PLAN"));


CREATE TABLE "ESTADO"
( "ID_ESTADO" NUMBER(∗,0) NOT NULL ENABLE,
"NOM_ESTADO" VARCHAR2(255),
CONSTRAINT "ESTADO_PK" PRIMARY KEY ("ID_ESTADO"));


CREATE TABLE "PLANIFICACION_ESTADO"
( "ID_PLAN" NUMBER(∗,0) NOT NULL ENABLE,
"ESTADO_ID_ESTADO" NUMBER(∗,0) NOT NULL ENABLE,
CONSTRAINT "PLANIFICACION_ESTADO_PK" PRIMARY KEY ("ID_PLAN",
"ESTADO_ID_ESTADO")
CONSTRAINT "FK_ASS_19" FOREIGN KEY ("ESTADO_ID_ESTADO")
REFERENCES "ESTADO" ("ID_ESTADO"),
CONSTRAINT "PLANIFICACION_ESTADO_PLAN_FK1" FOREIGN KEY ("
ID_PLAN")
REFERENCES "PLANIFICACION" ("ID_PLAN"));


CREATE TABLE "PLANIFICACION_ESTADO_FCAMBIO"
( "FCAMBIO" DATE NOT NULL ENABLE,
"ID_ESTADO" NUMBER(∗,0) NOT NULL ENABLE,
"ID_PLAN" NUMBER(∗,0) NOT NULL ENABLE,
CONSTRAINT "PLAN_ESTADO_FC_PK"
PRIMARY KEY ("FCAMBIO","ID_ESTADO","ID_PLAN"),
CONSTRAINT "PE_FCAMBIO_ESTADO_FK"
FOREIGN KEY ("ID_ESTADO")
REFERENCES "ESTADO" ("ID_ESTADO"),
CONSTRAINT "PE_FCAMBIO_PLANIFICACION_FK"
FOREIGN KEY ("ID_PLAN") REFERENCES "PLANIFICACION" ("ID_PLAN"));


CREATE TABLE "EVALUACION"
( "NUM_CORRELATIVO" NUMBER(∗,0) NOT NULL ENABLE,
"DV" CHAR(1 BYTE) NOT NULL ENABLE,
"PLANIFICACION_ID_PLAN" NUMBER(∗,0) NOT NULL ENABLE,
CONSTRAINT "EVALUACION_PK"
PRIMARY KEY ("NUM_CORRELATIVO", "DV","PLANIFICACION_ID_PLAN"),
CONSTRAINT "FK_ASS_43"
FOREIGN KEY ("PLANIFICACION_ID_PLAN")
REFERENCES "PLANIFICACION" ("ID_PLAN"),
CONSTRAINT "EVALUACION_NO_DOCENTE_FK1"
FOREIGN KEY ("NUM_CORRELATIVO", "DV")
REFERENCES "NO_DOCENTE" ("PERSONAL_NUM_CORRELATIVO", "
PERSONAL_DV"));


CREATE TABLE "PERIODO"
( "ID_PERIODO" NUMBER(∗,0) NOT NULL ENABLE,
"DURACION" NUMBER(∗,0),
"MES_INI" DATE,
"MER_TER" DATE,
"ID_PLAN" NUMBER(∗,0),
CONSTRAINT "PERIODO_PK" PRIMARY KEY ("ID_PERIODO"),
CONSTRAINT "PERIODO_PLAN_ANUAL_FK" FOREIGN KEY ("ID_PLAN")
REFERENCES "PLAN_ANUAL" ("PLANIFICACION_ID_PLAN"));


CREATE TABLE "EVALUACION_DETALLE"
( "FECHA_EVA" DATE NOT NULL ENABLE,
"COMENTARIO" VARCHAR2(255 BYTE),
"NUM_CORRELATIVO" NUMBER(∗,0) NOT NULL ENABLE,
"DV" CHAR(1 BYTE) NOT NULL ENABLE,
"ID_PLAN" NUMBER(∗,0) NOT NULL ENABLE,
CONSTRAINT "EVALUACION_DETALLE_PK" PRIMARY KEY ("FECHA_EVA
", "NUM_CORRELATIVO","DV", "ID_PLAN"),
CONSTRAINT "ED_NO_DOCENTE_FK" FOREIGN KEY ("
NUM_CORRELATIVO", "DV")
REFERENCES "NO_DOCENTE" ("PERSONAL_NUM_CORRELATIVO", "
PERSONAL_DV"),
CONSTRAINT "ED_PLANIFICACION_FK" FOREIGN KEY ("ID_PLAN")
REFERENCES "PLANIFICACION" ("ID_PLAN"));


CREATE TABLE "UNIDAD"
( "ID_UNIDAD" NUMBER(∗,0) NOT NULL ENABLE,
"FECHAI" DATE,
"FECHAT" DATE,
"ID_PLAN" NUMBER(∗,0),
CONSTRAINT "UNIDAD_PK" PRIMARY KEY ("ID_UNIDAD"),
CONSTRAINT "UNIDAD_PLAN_UNIDAD_FK" FOREIGN KEY ("ID_PLAN")
REFERENCES "PLAN_UNIDAD" ("PLANIFICACION_ID_PLAN"));


CREATE TABLE "CLASE"
( "ID_CLASE" NUMBER(∗,0) NOT NULL ENABLE,
"FECHA" DATE,
"DURACION" NUMBER(∗,0),
"DIA" NUMBER(∗,0),
"HI" DATE,
"HT" DATE,
"ID_PLAN" NUMBER(∗,0),
CONSTRAINT "CLASE_PK" PRIMARY KEY ("ID_CLASE"),
CONSTRAINT "CLASE_PLAN_CLASE_FK" FOREIGN KEY ("ID_PLAN")
REFERENCES "PLAN_CLASE" ("PLANIFICACION_ID_PLAN"));


CREATE TABLE "PERIODO_APREVIOS"
( "APREVIOS" VARCHAR2(1000 BYTE) NOT NULL ENABLE,
"ID_PERIODO" NUMBER(∗,0) NOT NULL ENABLE,
CONSTRAINT "PERIODO_APREVIOS_PK" PRIMARY KEY ("APREVIOS", "
ID_PERIODO"),
CONSTRAINT "PERIODO_APREVIOS_PERIODO_FK" FOREIGN KEY ("
ID_PERIODO")
REFERENCES "PERIODO" ("ID_PERIODO"));


CREATE TABLE "UNIDAD_APREVIOS"
( "APREVIOS" VARCHAR2(1000 BYTE) NOT NULL ENABLE,
"ID_UNIDAD" NUMBER(∗,0) NOT NULL ENABLE,
CONSTRAINT "UNIDAD_APREVIOS_PK" PRIMARY KEY ("ID_UNIDAD", "
APREVIOS"),
CONSTRAINT "UNIDAD_APREVIOS_UNIDAD_FK"
FOREIGN KEY ("ID_UNIDAD") REFERENCES "UNIDAD" ("ID_UNIDAD"));


CREATE TABLE "CLASE_APREVIOS"
( "APREVIOS" VARCHAR2(1000 BYTE) NOT NULL ENABLE,
"ID_CLASE" NUMBER(∗,0) NOT NULL ENABLE,
CONSTRAINT "CLASE_APREVIOS_PK" PRIMARY KEY ("APREVIOS", "
ID_CLASE"),
CONSTRAINT "CLASE_APREVIOS_CLASE_FK" FOREIGN KEY ("
ID_CLASE")
REFERENCES "CLASE" ("ID_CLASE"));


CREATE TABLE "METODOLOGIA"
( "ID_MET" NUMBER(∗,0) NOT NULL ENABLE,
"NOM_MET" VARCHAR2(255 BYTE),
"DESC_MET" VARCHAR2(500 BYTE),
CONSTRAINT "METODOLOGIA_PK" PRIMARY KEY ("ID_MET"));


CREATE TABLE "METODOLOGIA_PERIODO"
( "PERIODO_ID_PERIODO" NUMBER(∗,0) NOT NULL ENABLE,
"METODOLOGIA_ID_MET" NUMBER(∗,0) NOT NULL ENABLE,
CONSTRAINT "METODOLOGIA_PERIODO__IDX"
PRIMARY KEY ("PERIODO_ID_PERIODO","METODOLOGIA_ID_MET"),
CONSTRAINT "FK_ASS_44"
FOREIGN KEY ("PERIODO_ID_PERIODO")
REFERENCES "PERIODO" ("ID_PERIODO"),
CONSTRAINT "FK_ASS_45"
FOREIGN KEY ("METODOLOGIA_ID_MET")
REFERENCES "METODOLOGIA" ("ID_MET"));


CREATE TABLE "METODOLOGIA_UNIDAD"
( "UNIDAD_ID_UNIDAD" NUMBER(∗,0) NOT NULL ENABLE,
"METODOLOGIA_ID_MET" NUMBER(∗,0) NOT NULL ENABLE,
CONSTRAINT "METODOLOGIA_UNIDAD__IDX"
PRIMARY KEY ("UNIDAD_ID_UNIDAD",
"METODOLOGIA_ID_MET"),
CONSTRAINT "FK_ASS_46"
FOREIGN KEY ("UNIDAD_ID_UNIDAD")
REFERENCES "UNIDAD" ("ID_UNIDAD"),
CONSTRAINT "FK_ASS_47"
FOREIGN KEY ("METODOLOGIA_ID_MET")
REFERENCES "METODOLOGIA" ("ID_MET"));


CREATE TABLE "RECURSO"
( "ID_RECURSO" NUMBER(∗,0) NOT NULL ENABLE,
"NOM_REC" VARCHAR2(255 BYTE),
"DESC_REC" VARCHAR2(500 BYTE),
CONSTRAINT "RECURSO_PK"
PRIMARY KEY ("ID_RECURSO"));


CREATE TABLE "ACTIVIDAD"
( "ID_ACT" NUMBER(∗,0) NOT NULL ENABLE,
"DESC_ACT" VARCHAR2(500 BYTE),
"DURACION" NUMBER(∗,0),
"ID_CLASE" NUMBER(∗,0),
"ID_MET" NUMBER(∗,0),
CONSTRAINT "ACTIVIDAD_PK" PRIMARY KEY ("ID_ACT"),
CONSTRAINT "ACTIVIDAD_CLASE_FK" FOREIGN KEY ("ID_CLASE")
REFERENCES "CLASE" ("ID_CLASE"),
CONSTRAINT "ACTIVIDAD_METODOLOGIA_FK" FOREIGN KEY ("ID_MET")
REFERENCES "METODOLOGIA" ("ID_MET"));


CREATE TABLE "RECURSO_ACTIVIDAD"
( "RECURSO_ID_RECURSO" NUMBER(∗,0) NOT NULL ENABLE,
"ACTIVIDAD_ID_ACT" NUMBER(∗,0) NOT NULL ENABLE,
CONSTRAINT "RECURSO_ACTIVIDAD__IDX" PRIMARY KEY ("
RECURSO_ID_RECURSO",
"ACTIVIDAD_ID_ACT"),
CONSTRAINT "FK_ASS_50" FOREIGN KEY ("RECURSO_ID_RECURSO")
REFERENCES "RECURSO" ("ID_RECURSO"),
CONSTRAINT "FK_ASS_51" FOREIGN KEY ("ACTIVIDAD_ID_ACT")
REFERENCES "ACTIVIDAD" ("ID_ACT"));


CREATE TABLE "RECURSO_PERIODO"
( "PERIODO_ID_PERIODO" NUMBER(∗,0) NOT NULL ENABLE,
"RECURSO_ID_RECURSO" NUMBER(∗,0) NOT NULL ENABLE,
CONSTRAINT "RECURSO_PERIODO__IDX" PRIMARY KEY ("
PERIODO_ID_PERIODO",
"RECURSO_ID_RECURSO"),
CONSTRAINT "FK_ASS_52" FOREIGN KEY ("PERIODO_ID_PERIODO")
REFERENCES "PERIODO" ("ID_PERIODO"),
CONSTRAINT "FK_ASS_53" FOREIGN KEY ("RECURSO_ID_RECURSO")
REFERENCES "RECURSO" ("ID_RECURSO"));


CREATE TABLE "RECURSO_UNIDAD"
( "UNIDAD_ID_UNIDAD" NUMBER(∗,0) NOT NULL ENABLE,
"RECURSO_ID_RECURSO" NUMBER(∗,0) NOT NULL ENABLE,
CONSTRAINT "RECURSO_UNIDAD__IDX" PRIMARY KEY ("
UNIDAD_ID_UNIDAD",
"RECURSO_ID_RECURSO"),
CONSTRAINT "FK_ASS_54" FOREIGN KEY ("UNIDAD_ID_UNIDAD")
REFERENCES "UNIDAD" ("ID_UNIDAD"),
CONSTRAINT "FK_ASS_55" FOREIGN KEY ("RECURSO_ID_RECURSO")
REFERENCES "RECURSO" ("ID_RECURSO"));


CREATE TABLE "DETALLE_PROGRAMA_CLASE"
( "DETALLE_PROGRAMA_ID_DP" NUMBER(∗,0) NOT NULL ENABLE,
"CLASE_ID_CLASE" NUMBER(∗,0) NOT NULL ENABLE,
CONSTRAINT "DETALLE_PROGRAMA_CLASE__IDX" PRIMARY KEY
( "DETALLE_PROGRAMA_ID_DP", "CLASE_ID_CLASE"),
CONSTRAINT "FK_ASS_37" FOREIGN KEY ("CLASE_ID_CLASE")
REFERENCES "CLASE" ("ID_CLASE"),
CONSTRAINT "DETALLE_PROGRAMA_CLASE_DE_FK1" FOREIGN KEY ("
DETALLE_PROGRAMA_ID_DP")
REFERENCES "DETALLE_PROGRAMA" ("ID_DP"));


CREATE TABLE "DETALLE_PROGRAMA_PERIODO"
( "DETALLE_PROGRAMA_ID_DP" NUMBER(∗,0) NOT NULL ENABLE,
"PERIODO_ID_PERIODO" NUMBER(∗,0) NOT NULL ENABLE,
CONSTRAINT "DETALLE_PROGRAMA_PERIODO__IDX" PRIMARY KEY
( "DETALLE_PROGRAMA_ID_DP", "PERIODO_ID_PERIODO"),
CONSTRAINT "FK_ASS_39" FOREIGN KEY ("PERIODO_ID_PERIODO")
REFERENCES "PERIODO" ("ID_PERIODO"),
CONSTRAINT "DETALLE_PROGRAMA_PERIODO__FK1" FOREIGN KEY ("
DETALLE_PROGRAMA_ID_DP")
REFERENCES "DETALLE_PROGRAMA" ("ID_DP"));


CREATE TABLE "DETALLE_PROGRAMA_UNIDAD"
( "DETALLE_PROGRAMA_ID_DP" NUMBER(∗,0) NOT NULL ENABLE,
"UNIDAD_ID_UNIDAD" NUMBER(∗,0) NOT NULL ENABLE,
CONSTRAINT "DETALLE_PROGRAMA_UNIDAD__IDX" PRIMARY KEY
( "DETALLE_PROGRAMA_ID_DP", "UNIDAD_ID_UNIDAD"),
CONSTRAINT "FK_ASS_41" FOREIGN KEY ("UNIDAD_ID_UNIDAD")
REFERENCES "UNIDAD" ("ID_UNIDAD"),
CONSTRAINT "DETALLE_PROGRAMA_UNIDAD_D_FK1" FOREIGN KEY ("
DETALLE_PROGRAMA_ID_DP")
REFERENCES "DETALLE_PROGRAMA" ("ID_DP"));
