----------------------------------------------
--This project was develop using
--Oracle database 11g
----------------------------------------------
--For further information, please check the
--Readme, where i provided all the diagrams
--in order to understand the data model.
----------------------------------------------
@author DaRk452
@email imunoz@redeshost.cl
*/

CREATE OR REPLACE TYPE NIVEL_OB AS OBJECT (
ID_NIVEL NUMBER(10), NOM_NIVEL VARCHAR2(255));


CREATE OR REPLACE TYPE CURSO_OB AS OBJECT (
REFNIVEL REF NIVEL_OB,
ID_NIVEL NUMBER(10),
LETRA CHAR(1), YEAR_ DATE);


CREATE OR REPLACE TYPE CELULAR_PERSONA_OB AS OBJECT(
NUMERO_CELULAR NUMBER(10));


CREATE OR REPLACE TYPE CELULARES AS VARRAY(5) OF
CELULAR_PERSONA_OB;


CREATE OR REPLACE TYPE EMAIL_PERSONA_OB AS OBJECT (
CORREO VARCHAR2(500));


CREATE OR REPLACE TYPE MAILS AS VARRAY(5) OF
EMAIL_PERSONA_OB;


CREATE OR REPLACE TYPE RUT_PERSONA_OB AS OBJECT
( NUM_CORRELATIVO NUMBER(8),DV CHAR(1));


CREATE OR REPLACE TYPE NOMBRE_COMPLETO_PERSONA_OB AS
OBJECT (NOMBRES VARCHAR2(255),
APATERNO VARCHAR2(255),
AMATERNO VARCHAR2(255));


CREATE OR REPLACE TYPE DIRECCION_PERSONA_OB AS OBJECT
( CALLE VARCHAR2(500),
NUM VARCHAR2(10),
COD_POSTAL VARCHAR2(10),
CIUDAD VARCHAR2(255),
REGION VARCHAR2(255));


CREATE OR REPLACE TYPE CARGO_OB AS OBJECT(
ID_CARGO NUMBER(10),
NOM_C VARCHAR2(255),
DESC_C VARCHAR2(255));


CREATE OR REPLACE TYPE PERSONAL_OB AS OBJECT(
RUT RUT_PERSONA_OB,
NOMBRE_COMPLETO NOMBRE_COMPLETO_PERSONA_OB,
FNAC DATE,
DIRECCION DIRECCION_PERSONA_OB,
NUM_CELULARES CELULARES,
CORREOS MAILS,
MEMBER FUNCTION EDAD RETURN NUMBER)
NOT FINAL;


--Here we have a function that will return the
--Personal/staff's age, based is their birthday that is
--an attribute of the personal object (type)
CREATE OR REPLACE TYPE BODY PERSONAL_OB IS
MEMBER FUNCTION EDAD RETURN NUMBER IS
    BEGIN
        RETURN(TRUNC(MONTHS_BETWEEN(SYSDATE, SELF.FNAC) / 12));
    END;
END;


CREATE OR REPLACE TYPE DOCENTE_OB UNDER PERSONAL_OB(
CURSO_JEFE REF CURSO_OB);


CREATE OR REPLACE TYPE NO_DOCENTE_OB UNDER PERSONAL_OB(
CARGO REF CARGO_OB);

--Adding the head teacher from the course
ALTER TYPE CURSO_OB ADD ATTRIBUTE
(PROF_JEFE REF DOCENTE_OB) CASCADE;


CREATE OR REPLACE TYPE ASIGNATURA_OB AS OBJECT(
ID_ASIG NUMBER(10),
NOM_ASIG VARCHAR2(255),
CURSO_DICTA REF CURSO_OB,
PROFESOR_DICTA REF DOCENTE_OB);


CREATE OR REPLACE TYPE PROGRAMA_TIPO_OB AS OBJECT(
ID_PT NUMBER(10),
NOM_PT VARCHAR2(255),
ABREV VARCHAR2(10));


CREATE OR REPLACE TYPE DETALLE_PROGRAMA_OB AS OBJECT(
ID_DP NUMBER(10), NOM_DP VARCHAR2(255),
DESC_DP VARCHAR2(500),
ASIGNATURA REF ASIGNATURA_OB,
PROGRAMA_TIPO REF PROGRAMA_TIPO_OB);


CREATE OR REPLACE TYPE PLANIFICACION_OB AS OBJECT(
ID_PLAN NUMBER(10), ULT_MODIF DATE,
ULT_ESTADO VARCHAR2(30),
FCREACION DATE,
TIPO_PLAN VARCHAR2(10),
PROF_CREA REF DOCENTE_OB,
ASIGNATURA REF ASIGNATURA_OB) NOT FINAL;


CREATE OR REPLACE TYPE PLAN_ANUAL_OB UNDER
PLANIFICACION_OB() NOT FINAL;


CREATE OR REPLACE TYPE PLAN_UNIDAD_OB UNDER
PLANIFICACION_OB() NOT FINAL;


CREATE OR REPLACE TYPE PLAN_CLASE_OB UNDER
PLANIFICACION_OB() NOT FINAL;


CREATE OR REPLACE TYPE APREVIOS_OB AS OBJECT (
APRENDIZAJE_PREV VARCHAR2(1000));


CREATE OR REPLACE TYPE LISTADO_APREVIOS AS VARRAY(10) OF REF
APREVIOS_OB;


CREATE OR REPLACE TYPE PERIODO_OB AS OBJECT(
ID_PERIODO NUMBER(10),
DURACION NUMBER(3),
MES_INI DATE,
MES_TER DATE,
PLAN_ANUAL_PERTENECE REF PLAN_ANUAL_OB,
APREVIOS LISTADO_APREVIOS);


CREATE OR REPLACE TYPE UNIDAD_OB AS OBJECT(
ID_UNIDAD NUMBER(10),
FECHAI DATE,
FECHAT DATE,
PLAN_UNIDAD_PERTENECE REF PLAN_UNIDAD_OB,
APREVIOS LISTADO_APREVIOS);


CREATE OR REPLACE TYPE CLASE_OB AS OBJECT(
ID_CLASE NUMBER(10),
HORARIO HORARIO_CLASE_OB,
FECHA DATE,
PLAN_CLASE_PERTENECE REF PLAN_CLASE_OB,
APREVIOS LISTADO_APREVIOS);


CREATE OR REPLACE TYPE RECURSO_OB AS OBJECT(
ID_REC NUMBER(10),
NOM_REC VARCHAR2(100),
DESC_REC VARCHAR2(500));


CREATE OR REPLACE TYPE ACTIVIDAD_OB AS OBJECT(
ID_ACT NUMBER(10),
DESC_ACT VARCHAR2(500),
DURACION NUMBER(3),
CLASE_HECHA REF CLASE_OB);


--Period program detail type - intersection type for N: N relationship
CREATE OR REPLACE TYPE DETALLE_PROGRAMA_PERIODO_OB AS
OBJECT( DETALLE_PROGRAMA REF DETALLE_PROGRAMA_OB,
PERIODO REF PERIODO_OB);


--Unit program detail type - intersection type for N: N relationship
CREATE OR REPLACE TYPE DETALLE_PROGRAMA_UNIDAD_OB AS
OBJECT( DETALLE_PROGRAMA REF DETALLE_PROGRAMA_OB,
UNIDAD REF UNIDAD_OB);


--Class program detail type - intersection type for N: N relationship
CREATE OR REPLACE TYPE DETALLE_PROGRAMA_CLASE_OB AS
OBJECT(DETALLE_PROGRAMA REF DETALLE_PROGRAMA_OB,
CLASE REF CLASE_OB);


--Activity resource type - intersection type for N: N relationship
CREATE OR REPLACE TYPE RECURSO_ACTIVIDAD_OB AS
OBJECT(RECURSO REF RECURSO_OB, ACTIVIDAD REF ACTIVIDAD_OB);


--Period resource type - intersection type for N: N relationship
CREATE OR REPLACE TYPE RECURSO_PERIODO_OB AS
OBJECT(PERIODO REF PERIODO_OB, RECURSO REF RECURSO_OB);


--Unit resource type - intersection type for N: N relationship
CREATE OR REPLACE TYPE RECURSO_UNIDAD_OB AS
OBJECT(UNIDAD REF UNIDAD_OB,
RECURSO REF RECURSO_OB);


--Period methodology type - intersection type for N: N relationship
CREATE OR REPLACE TYPE METODOLOGIA_PERIODO_OB AS
OBJECT(PERIODO REF PERIODO_OB,
METODOLOGIA REF METODOLOGIA_OB);


--Unit methodology type - intersection type for N: N relationship
CREATE OR REPLACE TYPE METODOLOGIA_UNIDAD_OB AS OBJECT(
UNIDAD REF UNIDAD_OB, METODOLOGIA REF METODOLOGIA_OB);


CREATE OR REPLACE TYPE ACTIVIDADES_CLASE_OB AS VARRAY(5) OF
REF ACTIVIDAD_OB;


ALTER TYPE CLASE_OB ADD ATTRIBUTE (ACTIVIDADES
ACTIVIDADES_CLASE_OB) CASCADE;


ALTER TYPE METODOLOGIA_OB ADD ATTRIBUTE (ACTIVIDADES
ACTIVIDADES_CLASE_OB) CASCADE;


CREATE OR REPLACE TYPE DETALLES_PERIODOS AS VARRAY(15)
OF REF DETALLE_PROGRAMA_PERIODO_OB;


CREATE OR REPLACE TYPE DETALLES_UNIDADES AS VARRAY(15) OF
REF DETALLE_PROGRAMA_UNIDAD_OB;


CREATE OR REPLACE TYPE DETALLES_CLASES AS VARRAY(15) OF REF
DETALLE_PROGRAMA_CLASE_OB;


CREATE OR REPLACE TYPE RECURSOS_ACTIVIDADES AS VARRAY(15)
OF REF RECURSO_ACTIVIDAD_OB;


CREATE OR REPLACE TYPE RECURSOS_PERIODOS AS VARRAY(15) OF
REF RECURSO_PERIODO_OB;


CREATE OR REPLACE TYPE RECURSOS_UNIDADES AS VARRAY(15) OF
REF RECURSO_UNIDAD_OB;


CREATE OR REPLACE TYPE METODOLOGIAS_PERIODOS AS VARRAY(15)
OF REF METODOLOGIA_PERIODO_OB;


CREATE OR REPLACE TYPE METODOLOGIAS_UNIDADES AS VARRAY(15)
OF REF METODOLOGIA_UNIDAD_OB;


ALTER TYPE DETALLE_PROGRAMA_OB ADD ATTRIBUTE (PERIODOS
DETALLES_PERIODOS)CASCADE;


ALTER TYPE DETALLE_PROGRAMA_OB ADD ATTRIBUTE (UNIDADES
DETALLES_UNIDADES)CASCADE;


ALTER TYPE DETALLE_PROGRAMA_OB ADD ATTRIBUTE (CLASES
DETALLES_CLASES)CASCADE;


ALTER TYPE PERIODO_OB ADD ATTRIBUTE (DETALLES
DETALLES_PERIODOS)CASCADE;


ALTER TYPE UNIDAD_OB ADD ATTRIBUTE (DETALLES
DETALLES_UNIDADES)CASCADE;


ALTER TYPE CLASE_OB ADD ATTRIBUTE (DETALLES DETALLES_CLASES)
CASCADE;


ALTER TYPE PERIODO_OB ADD ATTRIBUTE (RECURSOS
RECURSOS_PERIODOS)CASCADE;


ALTER TYPE RECURSO_OB ADD ATTRIBUTE (PERIODOS
RECURSOS_PERIODOS)CASCADE;


ALTER TYPE UNIDAD_OB ADD ATTRIBUTE (RECURSOS
RECURSOS_UNIDADES)CASCADE;


ALTER TYPE RECURSO_OB ADD ATTRIBUTE (UNIDADES
RECURSOS_UNIDADES)CASCADE;


ALTER TYPE RECURSO_OB ADD ATTRIBUTE (ACTIVIDADES
RECURSOS_ACTIVIDADES)CASCADE;


ALTER TYPE ACTIVIDAD_OB ADD ATTRIBUTE (RECURSOS
RECURSOS_ACTIVIDADES)CASCADE;


CREATE OR REPLACE TYPE LISTADO_PERIODOS AS VARRAY(50) OF REF
PERIODO_OB;


CREATE OR REPLACE TYPE LISTADO_UNIDADES AS VARRAY(50) OF REF
UNIDAD_OB;


CREATE OR REPLACE TYPE LISTADO_CLASES AS VARRAY(50) OF REF
CLASE_OB;


ALTER TYPE PLAN_ANUAL_OB ADD ATTRIBUTE (PERIODOS
LISTADO_PERIODOS) CASCADE;


ALTER TYPE PLAN_UNIDAD_OB ADD ATTRIBUTE (UNIDADES
LISTADO_UNIDADES) CASCADE;


ALTER TYPE PLAN_CLASE_OB ADD ATTRIBUTE (CLASES
LISTADO_CLASES) CASCADE;


CREATE OR REPLACE TYPE ESTADO_OB AS OBJECT (
ID_ESTADO NUMBER(10), NOM_ESTADO VARCHAR(255));


CREATE OR REPLACE TYPE
FCAMBIO_ESTADO_PLAN AS OBJECT( FECHA_CAMBIO DATE);


CREATE OR REPLACE TYPE LISTADO_FCAMBIO_ESTADO AS VARRAY(20)
OF REF FCAMBIO_ESTADO_PLAN;


CREATE OR REPLACE TYPE EVALUACION_DETALLE_OB AS OBJECT(
FECHA_EVA DATE,
COMENTARIO VARCHAR2(500));


CREATE OR REPLACE TYPE LISTADO_EVALUACION_DETALLE AS VARRAY
(20) OF REF EVALUACION_DETALLE_OB;


CREATE OR REPLACE TYPE PLANIFICACION_ESTADO_OB AS OBJECT (
PLANIFICACION REF PLANIFICACION_OB, ESTADO REF ESTADO_OB,
LISTADO_FECHA_CAMBIOS LISTADO_FCAMBIO_ESTADO);


CREATE OR REPLACE TYPE LISTADO_PLAN_ESTADOS AS VARRAY(50) OF
REF PLANIFICACION_ESTADO_OB;


ALTER TYPE NO_DOCENTE_OB ADD
ATTRIBUTE (PLANIFICACIONES LISTADO_EVALUACIONES) CASCADE;


ALTER TYPE PLANIFICACION_OB ADD
ATTRIBUTE (EVALUADORES LISTADO_EVALUACIONES) CASCADE;


ALTER TYPE PLANIFICACION_OB ADD
ATTRIBUTE (ESTADOS LISTADO_PLAN_ESTADOS) CASCADE;


ALTER TYPE ESTADO_OB ADD
ATTRIBUTE (PLANIFICACIONES LISTADO_PLAN_ESTADOS) CASCADE;


CREATE OR REPLACE TYPE LISTADO_NO_DOCENTE AS
VARRAY(10) OF REF NO_DOCENTE_OB;


ALTER TYPE CARGO_OB ADD ATTRIBUTE (NO_DOCENTES
LISTADO_NO_DOCENTE) CASCADE;


CREATE OR REPLACE TYPE LISTADO_PLANIFICACIONES AS VARRAY
(100) OF REF PLANIFICACION_OB;


ALTER TYPE DOCENTE_OB ADD ATTRIBUTE (PLANIFICACIONES
LISTADO_PLAN_ESTADOS) CASCADE;


ALTER TYPE ASIGNATURA_OB ADD ATTRIBUTE (PLANIFICACIONES
LISTADO_PLANIFICACIONES) CASCADE;


CREATE OR REPLACE TYPE LISTADO_DETALLE_PROG AS
VARRAY(50) OF REF DETALLE_PROGRAMA_OB;


ALTER TYPE ASIGNATURA_OB ADD ATTRIBUTE (DETALLES
LISTADO_DETALLE_PROG) CASCADE;


CREATE OR REPLACE TYPE LISTADO_ASIGNATURAS AS
VARRAY(100) OF REF ASIGNATURA_OB;


ALTER TYPE CURSO_OB ADD ATTRIBUTE (ASIGNATURAS
LISTADO_ASIGNATURAS) CASCADE;


ALTER TYPE DOCENTE_OB ADD ATTRIBUTE (ASIGNATURAS
LISTADO_ASIGNATURAS) CASCADE;


CREATE OR REPLACE TYPE LISTADO_CURSOS AS
VARRAY(100) OF REF CURSO_OB;


ALTER TYPE NIVEL_OB ADD ATTRIBUTE (CURSOS LISTADO_CURSOS)
CASCADE;


-------------------------------------------
--Mapping the study case from OR to tables
--(persistence layer)
-------------------------------------------


CREATE TABLE NIVEL OF NIVEL_OB(
PRIMARY KEY(ID_NIVEL));


CREATE TABLE CURSO OF CURSO_OB (
ID_NIVEL SCOPE IS REFNIVEL,
PRIMARY KEY(ID_NIVEL,LETRA));


CREATE TABLE ASIGNATURA OF ASIGNATURA_OB(
PRIMARY KEY(ID_ASIG));


CREATE TABLE PERSONAL OF PERSONAL_OB(
PRIMARY KEY(RUT.NUM_CORRELATIVO,RUT.DV));


CREATE TABLE DOCENTE OF DOCENTE_OB(
PRIMARY KEY(RUT.NUM_CORRELATIVO,RUT.DV));


CREATE TABLE CARGO OF CARGO_OB(
PRIMARY KEY(ID_CARGO);


CREATE TABLE NO_DOCENTE OF DOCENTE_OB(
CARGO SCOPE IS CARGO,
PRIMARY KEY(RUT.NUM_CORRELATIVO,RUT.DV));


CREATE TABLE ESTADO OF ESTADO_OB (
PRIMARY KEY(ID_ESTADO));


CREATE TABLE PLANIFICACION OF PLANIFICACION_OB(
PRIMARY KEY(ID_PLAN));


CREATE TABLE PLAN_ANUAL OF PLAN_ANUAL_OB(
PRIMARY KEY(ID_PLAN));


CREATE TABLE PLAN_UNIDAD OF PLAN_UNIDAD_OB(
PRIMARY KEY(ID_PLAN));


CREATE TABLE PLAN_CLASE OF PLAN_CLASE_OB(
PRIMARY KEY(ID_PLAN));


CREATE TABLE PERIODO OF PERIODO_OB(
PLAN_ANUAL_PERTENECE SCOPE IS PLAN_ANUAL,
PRIMARY KEY(ID_PERIODO));


CREATE TABLE UNIDAD OF UNIDAD_OB(
PLAN_UNIDAD_PERTENECE SCOPE IS PLAN_UNIDAD,
PRIMARY KEY(ID_UNIDAD));


CREATE TABLE CLASE OF CLASE_OB(
PLAN_CLASE_PERTENECE SCOPE IS PLAN_CLASE,
PRIMARY KEY(ID_CLASE));


CREATE TABLE ACTIVIDAD OF ACTIVIDAD_OB (
PRIMARY KEY(ID_ASIG));


CREATE TABLE RECURSO OF RECURSO_OB(
PRIMARY KEY(ID_REC));


CREATE TABLE METODOLOGIA OF METODOLOGIA_OB(
PRIMARY KEY(ID_MET));


CREATE TABLE PROGRAMA_TIPO OF PROGRAMA_TIPO_OB(
PRIMARY KEY(ID_PT));


CREATE TABLE DETALLE_PROGRAMA OF DETALLE_PROGRAMA_OB(
PROGRAMA_TIPO SCOPE IS PROGRAMA_TIPO,
PRIMARY KEY(ID_DP));